eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
url: http://localhost:8080/product/reduceQuantity/{productId}?quantity={quantity}
updateURL: http://localhost:8080/product/update/{productId}?quantity={quantity}
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:Password123@microservice.5oi59xf.mongodb.net/?retryWrites=true&w=majority
